import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { team } from "./auth";

/**
 * Page module — operator-built marketing / activity landing pages
 * generated by an AI agent and rendered by the `apollokit-pages` worker.
 *
 * Five tables:
 *
 *  - `page_projects`              — project shell (slug = subdomain, auth mode,
 *                                   bound game modules, pointer to published version)
 *  - `page_project_versions`      — immutable schema snapshots; new draft / publish
 *                                   / rollback all append a new row
 *  - `page_project_conversations` — AI chat history; on reopen the admin UI
 *                                   replays this so the operator keeps iterating
 *  - `page_templates`             — official starter templates the operator
 *                                   picks when creating a project
 *  - `page_form_submissions`      — end-user form submissions captured by
 *                                   `activity-form` blocks
 *
 * Schema-level rules followed (apps/server/CLAUDE.md):
 *  - All tables are `page_*` prefixed.
 *  - End-user identifiers are `end_user_id` text columns, NEVER FK.
 *  - `publishedVersionId` and `parentVersionId` are intentionally NOT FK to
 *    avoid a circular FK between `page_projects` and `page_project_versions`,
 *    and to allow soft references for rollback lineage. Service layer keeps
 *    them consistent.
 */

export type PageAuthMode = "anonymous" | "platform_auth" | "hmac_external";
export type PageProjectStatus = "draft" | "published" | "archived";
export type PageVersionAuthorType = "ai" | "human";
export type PageConversationRole = "user" | "assistant" | "tool";

// ─── page_projects ────────────────────────────────────────────────

export const pageProjects = pgTable(
  "page_projects",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => team.id, { onDelete: "cascade" }),
    // Globally unique — used as subdomain `<slug>.pages.apollokit.dev`.
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    // 'draft' | 'published' | 'archived' — Zod-enforced at the validator layer.
    status: text("status").notNull().default("draft"),
    // 'anonymous' | 'platform_auth' | 'hmac_external'.
    authMode: text("auth_mode").notNull(),
    // Auto-provisioned cpk_/anonymous_cpk on project create. No FK because the
    // client_credentials table id is uuid but its lifecycle is owned by the
    // client-credentials module — we treat it as opaque here. Service layer
    // ensures the cred is revoked when the project is deleted.
    clientCredentialId: uuid("client_credential_id"),
    // Module names this project is allowed to bind blocks against
    // (e.g. ["check-in", "shop"]). Authoritative for proposePageDraft validation.
    boundModules: jsonb("bound_modules")
      .$type<string[]>()
      .notNull()
      .default([]),
    // Soft pointer to page_project_versions.id. Null = never published.
    publishedVersionId: uuid("published_version_id"),
    // SEO defaults / theme overrides / brand color / favicon URL …
    settings: jsonb("settings")
      .$type<Record<string, unknown>>()
      .notNull()
      .default({}),
    // Better Auth admin user id. Intentionally no FK — operator-account
    // deletion shouldn't cascade-wipe the projects they created.
    createdBy: text("created_by"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [
    // slug must be globally unique because it maps to a subdomain
    uniqueIndex("page_projects_slug_uidx").on(table.slug),
    index("page_projects_tenant_idx").on(table.tenantId, table.createdAt),
    index("page_projects_status_idx").on(table.tenantId, table.status),
  ],
);

// ─── page_project_versions ─────────────────────────────────────────

export const pageProjectVersions = pgTable(
  "page_project_versions",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    projectId: uuid("project_id")
      .notNull()
      .references(() => pageProjects.id, { onDelete: "cascade" }),
    // Monotonically increasing per project. Service uses
    // `MAX(version_number) + 1` inside an INSERT … SELECT to avoid races.
    versionNumber: integer("version_number").notNull(),
    // Free-form short label, e.g. "AI iteration 3", "manual edit",
    // "rollback to v2".
    label: text("label"),
    // Full PageProjectSchema JSON snapshot. Typed on the service side
    // because PageProjectSchema lives in `modules/page/types.ts`.
    schema: jsonb("schema")
      .$type<Record<string, unknown>>()
      .notNull(),
    // Soft reference to another versions.id — for rollback / branch lineage.
    // Not a FK so deleting a parent version doesn't break the chain.
    parentVersionId: uuid("parent_version_id"),
    // 'ai' | 'human'.
    authorType: text("author_type").notNull(),
    // Better Auth user id for human edits, or AI run id for ai-authored
    // versions. No FK either way.
    authorId: text("author_id"),
    // The conversation message that produced this version, if any.
    // Lets the admin UI link "v5 was generated by this message" both ways.
    conversationMessageId: text("conversation_message_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("page_project_versions_project_number_uidx").on(
      table.projectId,
      table.versionNumber,
    ),
    index("page_project_versions_project_created_idx").on(
      table.projectId,
      table.createdAt,
    ),
  ],
);

// ─── page_project_conversations ────────────────────────────────────

export const pageProjectConversations = pgTable(
  "page_project_conversations",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    projectId: uuid("project_id")
      .notNull()
      .references(() => pageProjects.id, { onDelete: "cascade" }),
    // ai-sdk message id — stable across resends, used for de-duping.
    messageId: text("message_id").notNull(),
    // 'user' | 'assistant' | 'tool'.
    role: text("role").notNull(),
    // ai-sdk UIMessage shape; includes text parts + tool calls + tool results.
    // Stored as opaque JSON; admin UI re-hydrates `useChat` from this.
    content: jsonb("content")
      .$type<Record<string, unknown>>()
      .notNull(),
    // If this assistant message triggered `proposePageDraft`, points at the
    // resulting versions row. Soft ref — version may be GC'd later but the
    // message stays.
    proposedVersionId: uuid("proposed_version_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("page_project_conversations_msg_uidx").on(
      table.projectId,
      table.messageId,
    ),
    index("page_project_conversations_project_created_idx").on(
      table.projectId,
      table.createdAt,
    ),
  ],
);

// ─── page_templates ────────────────────────────────────────────────

/**
 * Official / system-provided starter templates. MVP ships ~5–8 hand-written
 * official templates seeded on first deploy (see modules/page/seed-templates.ts).
 *
 * Templates are GLOBAL — there is no tenantId. Tenant-private templates are
 * a v2 concern and will get a separate `tenant_id` column + uniqueness rule.
 */
export const pageTemplates = pgTable(
  "page_templates",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    // 'checkin' | 'shop' | 'lottery' | 'redeem' | 'marketing' | … —
    // Zod-enforced at the validator layer.
    category: text("category").notNull(),
    coverImageUrl: text("cover_image_url"),
    // Full PageProjectSchema JSON.
    schema: jsonb("schema")
      .$type<Record<string, unknown>>()
      .notNull(),
    // Modules the template binds blocks against; project's boundModules
    // must be a superset to accept this template.
    requiredModules: jsonb("required_modules")
      .$type<string[]>()
      .notNull()
      .default([]),
    isOfficial: boolean("is_official").notNull().default(true),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [
    uniqueIndex("page_templates_slug_uidx").on(table.slug),
    index("page_templates_category_idx").on(table.category, table.sortOrder),
  ],
);

// ─── page_form_submissions ─────────────────────────────────────────

export const pageFormSubmissions = pgTable(
  "page_form_submissions",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    projectId: uuid("project_id")
      .notNull()
      .references(() => pageProjects.id, { onDelete: "cascade" }),
    // PageNode.id within the schema — opaque text, not a FK.
    pageId: text("page_id").notNull(),
    // BlockNode.id within the page — opaque text, not a FK.
    blockId: text("block_id").notNull(),
    // End-user opaque id (anonymous device cookie / Better Auth end-user /
    // pre-signed external user). NEVER FK — see CLAUDE.md "two userIds".
    endUserId: text("end_user_id"),
    payload: jsonb("payload")
      .$type<Record<string, unknown>>()
      .notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("page_form_submissions_project_created_idx").on(
      table.projectId,
      table.createdAt,
    ),
    index("page_form_submissions_block_idx").on(
      table.projectId,
      table.pageId,
      table.blockId,
    ),
  ],
);

// ─── $inferSelect re-exports ───────────────────────────────────────

export type PageProjectRow = typeof pageProjects.$inferSelect;
export type PageProjectVersionRow = typeof pageProjectVersions.$inferSelect;
export type PageProjectConversationRow =
  typeof pageProjectConversations.$inferSelect;
export type PageTemplateRow = typeof pageTemplates.$inferSelect;
export type PageFormSubmissionRow = typeof pageFormSubmissions.$inferSelect;
