import type { RequestIdVariables } from "hono/request-id";

import type { auth } from "./auth";

/**
 * Better Auth's `auth.$Infer.Session` is the officially recommended type
 * entry-point (see https://better-auth.com/docs/concepts/typescript), but
 * it has a known caveat:
 *
 *   > The session object does not automatically infer fields added by
 *   > plugins.
 *   — https://better-auth.com/docs/concepts/session-management#caveats
 *
 * The `organization` plugin adds `activeOrganizationId` (and `activeTeamId`
 * when teams are enabled) to the session table at the *schema* layer
 * (see `src/schema/auth.ts → session.activeOrganizationId`), and the
 * `databaseHooks.session.create.before` hook in `src/auth.ts` populates
 * it on every sign-in — so the runtime value is always there. The type
 * layer just doesn't know.
 *
 * Rather than reach for the heavier `customSession(..., options)`
 * workaround, we patch the gap here with an intersection that mirrors the
 * schema. Keep this in sync with what the organization plugin adds — if
 * we later enable teams, add `activeTeamId: string | null` here too.
 */
type InferredSession = typeof auth.$Infer.Session.session & {
  activeOrganizationId: string | null;
};
type InferredUser = typeof auth.$Infer.Session.user;

export type AuthMethod = "session" | "admin-api-key" | "client-credential";

/**
 * Client-credential context placed by `require-client-credential` middleware.
 * Keep this field-for-field compatible with the row selection the middleware
 * does — adding a column here requires adding it to the `.select()` shape
 * too, otherwise downstream routes reading `c.var.clientCredential.<field>`
 * will type-check but be `undefined` at runtime.
 */
export type ClientCredentialContext = {
  id: string;
  organizationId: string;
  publishableKey: string;
  enabled: boolean;
  expiresAt: Date | null;
  devMode: boolean;
};

/**
 * How `requireClientUser` resolved the end-user identity on this request.
 *
 * - `session` — the player is logged in via the end-user Better Auth
 *   instance; `c.var.endUserId` came from the cookie/bearer session.
 * - `hmac` — the player was synced in via `POST /api/users/sync` (or is
 *   still pre-sync) and the game client signs `endUserId` with the
 *   tenant's `csk_`.
 *
 * Most handlers don't need to care. Sync-only handlers that want to
 * refuse managed players (or vice versa) can branch on this.
 */
export type EndUserAuthMethod = "session" | "hmac";

export type HonoEnv = {
  // `Bindings` mirrors `CloudflareBindings` (auto-generated by
  // `wrangler types` into `worker-configuration.d.ts` and augmented by
  // `src/env-bindings.d.ts`). Required so `c.env.HYPERDRIVE` (and any
  // future binding read from middleware) is typed at the call site
  // instead of `unknown`.
  Bindings: CloudflareBindings;
  Variables: RequestIdVariables & {
    user: InferredUser | null;
    session: InferredSession | null;
    authMethod: AuthMethod | null;
    clientCredential: ClientCredentialContext | null;
    endUserId?: string;
    endUserAuthMethod?: EndUserAuthMethod;
  };
};
