import type { AuthLocalization } from '@daveyplate/better-auth-ui'

export const authLocalizationZh: AuthLocalization = {
  // ── Error messages ──
  INVALID_USERNAME_OR_PASSWORD: '用户名或密码错误',
  EMAIL_NOT_VERIFIED: '邮箱未验证',
  UNEXPECTED_ERROR: '发生意外错误',
  USERNAME_IS_ALREADY_TAKEN: '用户名已被使用',
  USERNAME_TOO_SHORT: '用户名太短',
  USERNAME_TOO_LONG: '用户名太长',
  INVALID_USERNAME: '用户名无效',
  INVALID_EMAIL: '邮箱地址无效',
  USER_NOT_FOUND: '用户未找到',
  TOO_MANY_ATTEMPTS: '尝试次数过多',
  USER_BANNED: '用户已被封禁',
  BANNED_USER: '该用户已被封禁',
  SESSION_EXPIRED: '会话已过期',
  INVALID_PASSWORD: '密码无效',
  INVALID_EMAIL_OR_PASSWORD: '邮箱或密码错误',
  PASSWORD_TOO_SHORT: '密码太短',
  PASSWORD_TOO_LONG: '密码太长',
  USER_ALREADY_EXISTS: '用户已存在',
  INVALID_TOKEN: '令牌无效',
  FAILED_TO_CREATE_USER: '创建用户失败',
  FAILED_TO_CREATE_SESSION: '创建会话失败',
  FAILED_TO_UPDATE_USER: '更新用户失败',
  FAILED_TO_GET_SESSION: '获取会话失败',
  CREDENTIAL_ACCOUNT_NOT_FOUND: '未找到凭据账户',
  ACCOUNT_NOT_FOUND: '账户未找到',
  SOCIAL_ACCOUNT_ALREADY_LINKED: '社交账户已关联',
  PROVIDER_NOT_FOUND: '提供商未找到',
  FAILED_TO_UNLINK_LAST_ACCOUNT: '无法取消关联最后一个账户',
  USER_ALREADY_HAS_PASSWORD: '用户已设置密码',
  EMAIL_CAN_NOT_BE_UPDATED: '邮箱无法更新',
  RATE_LIMIT_EXCEEDED: '请求频率超限',
  UNKNOWN_ERROR: '未知错误',
  SERVICE_UNAVAILABLE: '服务不可用',
  VERIFICATION_FAILED: '验证失败',
  INVALID_SESSION_TOKEN: '会话令牌无效',
  PASSWORD_COMPROMISED: '密码已泄露',

  // ── Organization errors ──
  YOU_ARE_NOT_ALLOWED_TO_CREATE_A_NEW_ORGANIZATION: '您无权创建新公司',
  YOU_HAVE_REACHED_THE_MAXIMUM_NUMBER_OF_ORGANIZATIONS: '已达到公司数量上限',
  ORGANIZATION_ALREADY_EXISTS: '公司已存在',
  ORGANIZATION_NOT_FOUND: '公司未找到',
  USER_IS_NOT_A_MEMBER_OF_THE_ORGANIZATION: '用户不是该公司的成员',
  YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_ORGANIZATION: '您无权更新此公司',
  YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_ORGANIZATION: '您无权删除此公司',
  NO_ACTIVE_ORGANIZATION: '没有活跃的公司',
  USER_IS_ALREADY_A_MEMBER_OF_THIS_ORGANIZATION: '用户已是该公司成员',
  MEMBER_NOT_FOUND: '成员未找到',
  ROLE_NOT_FOUND: '角色未找到',
  YOU_CANNOT_LEAVE_THE_ORGANIZATION_AS_THE_ONLY_OWNER: '您是唯一的所有者，无法离开公司',
  YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_MEMBER: '您无权删除此成员',
  YOU_ARE_NOT_ALLOWED_TO_INVITE_USERS_TO_THIS_ORGANIZATION: '您无权邀请用户加入此公司',
  USER_IS_ALREADY_INVITED_TO_THIS_ORGANIZATION: '用户已被邀请加入此公司',
  INVITATION_NOT_FOUND: '邀请未找到',
  YOU_ARE_NOT_THE_RECIPIENT_OF_THE_INVITATION: '您不是此邀请的接收者',
  YOU_ARE_NOT_ALLOWED_TO_CANCEL_THIS_INVITATION: '您无权取消此邀请',
  INVITER_IS_NO_LONGER_A_MEMBER_OF_THE_ORGANIZATION: '邀请者已不再是公司成员',
  YOU_ARE_NOT_ALLOWED_TO_INVITE_USER_WITH_THIS_ROLE: '您无权以此角色邀请用户',
  FAILED_TO_RETRIEVE_INVITATION: '获取邀请失败',
  YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_MEMBER: '您无权更新此成员',
  ORGANIZATION_MEMBERSHIP_LIMIT_REACHED: '公司成员数量已达上限',
  NOT_ORGANIZATION_MEMBER: '不是公司成员',
  INVITATION_LIMIT_REACHED: '邀请数量已达上限',

  // ── UI strings ──
  APP: '应用',
  ACCOUNT: '账户',
  ACCOUNTS: '账户',
  ACCOUNTS_DESCRIPTION: '管理您当前登录的账户。',
  ACCOUNTS_INSTRUCTIONS: '登录其他账户。',
  ADD_ACCOUNT: '添加账户',
  ALREADY_HAVE_AN_ACCOUNT: '已有账户？',
  AVATAR: '头像',
  AVATAR_DESCRIPTION: '点击头像上传自定义头像。',
  AVATAR_INSTRUCTIONS: '头像为可选，但强烈建议设置。',
  CANCEL: '取消',
  CHANGE_PASSWORD: '修改密码',
  CHANGE_PASSWORD_DESCRIPTION: '输入当前密码和新密码。',
  CHANGE_PASSWORD_INSTRUCTIONS: '请使用至少 8 个字符。',
  CHANGE_PASSWORD_SUCCESS: '密码已修改。',
  CONFIRM_PASSWORD: '确认密码',
  CONFIRM_PASSWORD_PLACEHOLDER: '确认密码',
  CONFIRM_PASSWORD_REQUIRED: '请确认密码',
  COPIED_TO_CLIPBOARD: '已复制到剪贴板',
  COPY_TO_CLIPBOARD: '复制到剪贴板',
  CONTINUE: '继续',
  CURRENT_PASSWORD: '当前密码',
  CURRENT_PASSWORD_PLACEHOLDER: '当前密码',
  CURRENT_SESSION: '当前会话',
  UPDATE: '更新',
  DELETE: '删除',
  DELETE_AVATAR: '删除头像',
  DELETE_ACCOUNT: '删除账户',
  DELETE_ACCOUNT_DESCRIPTION: '永久删除您的账户及所有内容。此操作不可逆，请谨慎操作。',
  DELETE_ACCOUNT_INSTRUCTIONS: '请确认删除您的账户。此操作不可逆，请谨慎操作。',
  DELETE_ACCOUNT_SUCCESS: '您的账户已被删除。',
  DONT_HAVE_AN_ACCOUNT: '没有账户？',
  DONE: '完成',
  EMAIL: '邮箱',
  EMAIL_DESCRIPTION: '输入您要用于登录的邮箱地址。',
  EMAIL_INSTRUCTIONS: '请输入有效的邮箱地址。',
  EMAIL_IS_THE_SAME: '邮箱相同',
  EMAIL_PLACEHOLDER: 'name@example.com',
  EMAIL_REQUIRED: '请输入邮箱地址',
  EMAIL_VERIFY_CHANGE: '请查看邮箱以验证更改。',
  EMAIL_VERIFICATION: '邮箱验证',
  EMAIL_VERIFICATION_DESCRIPTION: '请查看邮箱中的验证码以完成注册。',
  EMAIL_VERIFICATION_SUCCESS: '邮箱验证成功。',
  IS_INVALID: '无效',
  IS_REQUIRED: '为必填项',
  IS_THE_SAME: '相同',
  FORGOT_PASSWORD: '忘记密码',
  FORGOT_PASSWORD_ACTION: '发送重置链接',
  FORGOT_PASSWORD_DESCRIPTION: '输入邮箱以重置密码',
  FORGOT_PASSWORD_EMAIL: '请查看邮箱中的密码重置链接。',
  FORGOT_PASSWORD_LINK: '忘记密码？',
  LINK: '关联',
  NAME: '姓名',
  NAME_DESCRIPTION: '请输入您的全名或显示名称。',
  NAME_INSTRUCTIONS: '请使用不超过 32 个字符。',
  NAME_PLACEHOLDER: '姓名',
  NEW_PASSWORD: '新密码',
  NEW_PASSWORD_PLACEHOLDER: '新密码',
  NEW_PASSWORD_REQUIRED: '请输入新密码',
  OR_CONTINUE_WITH: '或通过以下方式继续',
  PASSKEY: '通行密钥',
  PASSKEYS: '通行密钥',
  PASSKEYS_DESCRIPTION: '管理您的通行密钥以安全访问。',
  PASSKEYS_INSTRUCTIONS: '无需密码即可安全访问您的账户。',
  PASSWORD: '密码',
  PASSWORD_PLACEHOLDER: '密码',
  PASSWORD_REQUIRED: '请输入密码',
  PASSWORDS_DO_NOT_MATCH: '两次密码不一致',
  PROVIDERS: '关联账户',
  PROVIDERS_DESCRIPTION: '将您的账户与第三方服务关联。',
  REMEMBER_ME: '记住我',
  RESEND_CODE: '重新发送验证码',
  RESEND_VERIFICATION_EMAIL: '重新发送验证邮件',
  RESET_PASSWORD: '重置密码',
  RESET_PASSWORD_ACTION: '保存新密码',
  RESET_PASSWORD_DESCRIPTION: '在下方输入您的新密码',
  RESET_PASSWORD_SUCCESS: '密码重置成功',
  REQUEST_FAILED: '请求失败',
  REVOKE: '撤销',
  SIGN_IN: '登录',
  SIGN_IN_ACTION: '登录',
  SIGN_IN_DESCRIPTION: '输入邮箱登录您的账户',
  SIGN_IN_WITH: '通过以下方式登录',
  SIGN_OUT: '退出登录',
  SIGN_UP: '注册',
  SIGN_UP_ACTION: '创建账户',
  SIGN_UP_DESCRIPTION: '输入您的信息以创建账户',
  SIGN_UP_EMAIL: '请查看邮箱中的验证链接。',
  SESSIONS: '会话',
  SESSIONS_DESCRIPTION: '管理您的活跃会话并撤销访问。',
  SET_PASSWORD: '设置密码',
  SET_PASSWORD_DESCRIPTION: '点击下方按钮，通过邮件设置您的账户密码。',
  SETTINGS: '设置',
  SAVE: '保存',
  SECURITY: '安全',
  SWITCH_ACCOUNT: '切换账户',
  TRUST_DEVICE: '信任此设备',
  UPDATED_SUCCESSFULLY: '更新成功',
  USERNAME: '用户名',
  USERNAME_DESCRIPTION: '输入您要用于登录的用户名。',
  USERNAME_INSTRUCTIONS: '请使用不超过 32 个字符。',
  USERNAME_PLACEHOLDER: '用户名',
  SIGN_IN_USERNAME_PLACEHOLDER: '用户名或邮箱',
  SIGN_IN_USERNAME_DESCRIPTION: '输入用户名或邮箱登录您的账户',
  OPTIONAL_BRACKETS: '（可选）',
  VERIFY_YOUR_EMAIL: '验证您的邮箱',
  VERIFY_YOUR_EMAIL_DESCRIPTION: '请验证您的邮箱地址。检查收件箱中的验证邮件。如果没有收到，请点击下方按钮重新发送。',
  GO_BACK: '返回',
  SESSION_NOT_FRESH: '您的会话已过期，请重新登录。',
  UPLOAD_AVATAR: '上传头像',
  UPLOAD: '上传',
  PRIVACY_POLICY: '隐私政策',
  TERMS_OF_SERVICE: '服务条款',
  BY_CONTINUING_YOU_AGREE: '继续即表示您同意',
  USER: '用户',

  // ── Organization UI ──
  CREATE_ORGANIZATION: '创建公司',
  ORGANIZATION: '公司',
  ORGANIZATION_NAME: '名称',
  ORGANIZATION_NAME_PLACEHOLDER: '我的公司',
  ORGANIZATION_NAME_DESCRIPTION: '这是您的公司显示名称。',
  ORGANIZATION_NAME_INSTRUCTIONS: '请使用不超过 32 个字符。',
  ORGANIZATION_SLUG: 'URL 标识',
  ORGANIZATION_SLUG_DESCRIPTION: '这是您的公司 URL 命名空间。',
  ORGANIZATION_SLUG_INSTRUCTIONS: '请使用不超过 48 个字符。',
  ORGANIZATION_SLUG_PLACEHOLDER: 'acme',
  CREATE_ORGANIZATION_SUCCESS: '公司创建成功',
  ORGANIZATIONS: '公司',
  ORGANIZATIONS_DESCRIPTION: '管理您的公司和成员资格。',
  ORGANIZATIONS_INSTRUCTIONS: '创建公司以与其他用户协作。',
  LEAVE_ORGANIZATION: '离开公司',
  LEAVE_ORGANIZATION_CONFIRM: '确定要离开此公司吗？',
  LEAVE_ORGANIZATION_SUCCESS: '已成功离开公司。',
  MANAGE_ORGANIZATION: '管理公司',
  REMOVE_MEMBER: '移除成员',
  REMOVE_MEMBER_CONFIRM: '确定要从公司中移除此成员吗？',
  REMOVE_MEMBER_SUCCESS: '成员已移除',
  INVITE_MEMBER: '邀请成员',
  MEMBERS: '成员',
  MEMBERS_DESCRIPTION: '添加或移除成员并管理其角色。',
  MEMBERS_INSTRUCTIONS: '邀请新成员加入您的公司。',
  INVITE_MEMBER_DESCRIPTION: '发送邀请以添加新成员到您的公司。',
  ROLE: '角色',
  SELECT_ROLE: '选择角色',
  ADMIN: '管理员',
  MEMBER: '成员',
  GUEST: '访客',
  OWNER: '所有者',
  UPDATE_ROLE_DESCRIPTION: '更新此成员的角色',
  UPDATE_ROLE: '更新角色',
  MEMBER_ROLE_UPDATED: '成员角色已更新',
  SEND_INVITATION: '发送邀请',
  SEND_INVITATION_SUCCESS: '邀请发送成功',
  PENDING_INVITATIONS: '待处理的邀请',
  PENDING_INVITATIONS_DESCRIPTION: '管理公司的待处理邀请。',
  PENDING_USER_INVITATIONS_DESCRIPTION: '您收到的公司邀请。',
  CANCEL_INVITATION: '取消邀请',
  INVITATION_CANCELLED: '邀请已取消',
  ACCEPT_INVITATION: '接受邀请',
  ACCEPT_INVITATION_DESCRIPTION: '您已被邀请加入一个公司。',
  INVITATION_ACCEPTED: '邀请已接受',
  INVITATION_REJECTED: '邀请已拒绝',
  ACCEPT: '接受',
  REJECT: '拒绝',
  INVITATION_EXPIRED: '此邀请已过期',
  DELETE_ORGANIZATION: '删除公司',
  DELETE_ORGANIZATION_DESCRIPTION: '永久删除您的公司及所有内容。此操作不可逆，请谨慎操作。',
  DELETE_ORGANIZATION_SUCCESS: '公司已删除',
  DELETE_ORGANIZATION_INSTRUCTIONS: '输入公司标识以继续：',
  SLUG_REQUIRED: '请输入公司标识',
  SLUG_DOES_NOT_MATCH: '标识不匹配',
  PERSONAL_ACCOUNT: '个人账户',

  // ── API Keys UI ──
  API_KEYS: 'API 密钥',
  API_KEYS_DESCRIPTION: '管理您的 API 密钥以安全访问。',
  API_KEYS_INSTRUCTIONS: '生成 API 密钥以编程方式访问您的账户。',
  CREATE_API_KEY: '创建 API 密钥',
  CREATE_API_KEY_DESCRIPTION: '为您的 API 密钥输入一个唯一名称以区分其他密钥。',
  API_KEY_NAME_PLACEHOLDER: '新 API 密钥',
  API_KEY_CREATED: 'API 密钥已创建',
  CREATE_API_KEY_SUCCESS: '请复制您的 API 密钥并保存在安全的地方。出于安全原因，我们无法再次显示。',
  NEVER_EXPIRES: '永不过期',
  EXPIRES: '过期',
  NO_EXPIRATION: '无过期时间',
  DELETE_API_KEY: '删除 API 密钥',
  DELETE_API_KEY_CONFIRM: '确定要删除此 API 密钥吗？',
  API_KEY: 'API 密钥',

  // ── Misc ──
  UNKNOWN: '未知',
  MEMBER_SINGULAR: '位成员',
  MEMBER_PLURAL: '位成员',
  ADD: '添加',
  REMOVE: '移除',


  // ── Team (= 项目) ──
  TEAM_LIMIT_REACHED: '项目数量已达上限',
  TEAM_MEMBER_LIMIT_REACHED: '项目成员数量已达上限',
  TEAM_NOT_FOUND: '项目未找到',
  TEAM_MEMBER_NOT_FOUND: '项目成员未找到',
  TEAM_NAME_TOO_LONG: '项目名称过长',
  ALREADY_TEAM_MEMBER: '已是项目成员',
  INSUFFICIENT_TEAM_PERMISSIONS: '项目权限不足',
  TEAM_ALREADY_EXISTS: '项目已存在',
  YOU_HAVE_REACHED_THE_MAXIMUM_NUMBER_OF_TEAMS: '已达到项目数量上限',
  YOU_ARE_NOT_ALLOWED_TO_CREATE_TEAMS_IN_THIS_ORGANIZATION: '您无权在此公司下创建项目',
  YOU_ARE_NOT_ALLOWED_TO_DELETE_TEAMS_IN_THIS_ORGANIZATION: '您无权删除此公司的项目',
  TEAMS: '项目',
  TEAM_ACTIVE: '当前项目',
  TEAM_SET_ACTIVE: '设为当前项目',
  CREATE_TEAM: '创建项目',
  CREATE_TEAM_INSTRUCTIONS: '建立新项目以隔离游戏数据、成员与集成。',
  CREATE_TEAM_SUCCESS: '项目创建成功',
  UPDATE_TEAM: '更新项目',
  UPDATE_TEAMS: '项目',
  UPDATE_TEAMS_DESCRIPTION: '管理此公司下的项目。',
  UPDATE_TEAM_DESCRIPTION: '重命名或更改此项目的标签。',
  UPDATE_TEAM_SUCCESS: '项目已更新',
  DELETE_TEAM: '删除项目',
  DELETE_TEAM_DESCRIPTION: '永久删除此项目及其所有相关记录(活动 / 物品 / 玩家 / 审计日志 等)。此操作不可逆。',
  DELETE_TEAM_INSTRUCTIONS: '输入项目名称以继续：',
  DELETE_TEAM_SUCCESS: '项目已删除',
  REMOVE_TEAM_CONFIRM: '确定要移除此项目吗？',
  SELECT_TEAMS: '选择项目',
  TEAM_NAME: '项目名称',
  TEAM_NAME_DESCRIPTION: '这是您的项目显示名称。',
  TEAM_NAME_INSTRUCTIONS: '请使用不超过 32 个字符。',
  TEAM_NAME_PLACEHOLDER: '我的游戏',
  TEAM_NAME_REQUIRED: '请输入项目名称',
  TEAM_NAME_DOES_NOT_MATCH: '项目名称不匹配',
  TEAM_MEMBERS: '项目成员',
  TEAM_MEMBERS_DESCRIPTION: '管理此项目的成员。',
  ADD_TEAM_MEMBER: '添加项目成员',
  ADD_TEAM_MEMBER_SUCCESS: '项目成员已添加',
  REMOVE_TEAM_MEMBER: '移除项目成员',
  REMOVE_TEAM_MEMBER_CONFIRM: '确定要移除此项目成员吗？',
  REMOVE_TEAM_MEMBER_SUCCESS: '项目成员已移除',
  MANAGE_TEAM_MEMBERS: '管理项目成员',
  MANAGE_TEAM_MEMBERS_DESCRIPTION: '邀请、变更角色或移除此项目的成员。',

  // ── Logo ──
  LOGO: 'Logo',
  LOGO_DESCRIPTION: '点击 Logo 上传自定义图片。',
  LOGO_INSTRUCTIONS: 'Logo 为可选，但强烈建议设置。',
  UPLOAD_LOGO: '上传 Logo',
  DELETE_LOGO: '删除 Logo',
}
